name: Deploy to Firebase (Test)

on:
  workflow_dispatch:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    environment: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Create environment.test.ts
        run: |
          cat <<EOF > src/environments/environment.test.ts
          export const environment = {
            production: false,
            imageProvider: 'google',
            firebaseConfig: {
              apiKey: "${{ secrets.FIREBASE_API_KEY }}",
              authDomain: "${{ secrets.FIREBASE_AUTH_DOMAIN }}",
              projectId: "${{ secrets.FIREBASE_PROJECT_ID }}",
              storageBucket: "${{ secrets.FIREBASE_STORAGE_BUCKET }}",
              messagingSenderId: "${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}",
              appId: "${{ secrets.FIREBASE_APP_ID }}",
              measurementId: "${{ secrets.FIREBASE_MEASUREMENT_ID }}"
            },
            openAIConfig: {
              apiKey: "${{ secrets.OPENAI_API_KEY }}",
              apiUrl: "${{ secrets.OPENAI_API_URL }}",
              aiImageApiUrl: "${{ secrets.OPENAI_API_IMAGE_URL }}"
            },
            googleConfig: {
              apiKey: "${{ secrets.GOOGLE_API_KEY }}",
              cseId: "${{ secrets.GOOGLE_CSE_ID }}"
            },
            stabilityConfig: {
              apiKey: "${{ secrets.STABILITY_API_KEY }}",
              apiUrl: "${{ secrets.STABILITY_API_URL }}"
            },
            fluxConfig: {
              apiKey: "${{ secrets.FLUX_API_KEY }}",
              apiUrl: "${{ secrets.FLUX_API_URL }}",
              model: "${{ secrets.FLUX_MODEL }}"
            }
          };
          EOF

      - name: Build Angular app
        run: npm run build -- --configuration=test

      - name: Deploy to Firebase (Test)
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_TEST }}
          projectId: story-maker-test
          channelId: live
