name: Deploy to Firebase (Test Only)

on:
  workflow_dispatch:
  push:
    branches:
      - develop # Deploy to test

jobs:
  build:
    runs-on: ubuntu-latest
    environment: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Create environment.test.ts
        run: |
          cat <<EOF > src/environments/environment.test.ts
          export const environment = {
            production: false,
            firebaseConfig: {
              apiKey: "${{ secrets.FIREBASE_API_KEY }}",
              authDomain: "${{ secrets.FIREBASE_AUTH_DOMAIN }}",
              projectId: "${{ secrets.FIREBASE_PROJECT_ID }}",
              storageBucket: "${{ secrets.FIREBASE_STORAGE_BUCKET }}",
              messagingSenderId: "${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}",
              appId: "${{ secrets.FIREBASE_APP_ID }}",
              measurementId: "${{ secrets.FIREBASE_MEASUREMENT_ID }}"
            },
            openAIConfig: {
              apiKey: "${{ secrets.OPENAI_API_KEY }}",
              apiUrl: "${{ secrets.OPENAI_API_URL }}"
            },
            googleConfig: {
              apiKey: "${{ secrets.GOOGLE_API_KEY }}",
              cseId: "${{ secrets.GOOGLE_CSE_ID }}"
            }
          };
          EOF

      - name: Debug: Check if environment.test.ts exists
        run: |
          if [ -f src/environments/environment.test.ts ]; then
            echo "✅ environment.test.ts exists!"
            cat src/environments/environment.test.ts
          else
            echo "❌ environment.test.ts is missing!"
            exit 1
          fi
          
      - name: Build Angular app
        run: npm run build -- --configuration=test

      - name: Verify Build Output
        run: |
          echo "Checking compiled output for environment variables..."
          grep -R "firebaseConfig" dist/story-maker
          
      - name: Deploy to Firebase (Test)
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          channelId: test
